aatoon_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('',views.home, name='home'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail')
    
]

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=200)
    created_at = models.DateField(auto_now_add=True)
    content = models.TextField(max_length=550)

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(request):
    #blogs = Blog.objects.order_by('-created_at')[:3]
    blogs = Blog.objects.order_by('-created_at')
    return render(request, 'blog/all_blogs.html',{'blogs':blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

#homepage
def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects':projects})

blog/templates/blog/all_blogs.html
<h2>Our blogs</h2>

<h2>Total blog {{ blogs.count|pluralize }} {{ blogs.count }} </h2>

{% for blog in blogs %}

<a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
<h5>{{ blog.created_at|date:'M d Y'|upper }}</h5>
<p>{{ blog.content|safe|truncatechars:50 }}</p>
{% endfor %}

blog/templates/blog/detail.html
<h1>{{ blog.title }}</h1>
<h2>{{ blog.created_at|date:'F jS Y' }}</h2>
{{ blog.content|safe }}

portfolio/templates/portfolio/home.html
<h2>Website Homepage</h2>
<a href="{% url 'blog:all_blogs' %}">Blog</a>
{% for project in projects %}

<h2>{{ project.title }}</h2>
<p>{{ project.description }}</p>
<img src="{{ project.image.url }}" width="300" height="300">
{% if project.url %}
<br><a href="{{ project.url }}" target="_blank">Project Link</a>
{% endif %}
{% endfor %}